debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*" # 액츄에이터의 엔드 포인트 중 숨겨져 있는 것들을 모두 활성화 / 개발 단계에서 보고 싶은 모든 기능을 볼 수 있다

logging:
  level:
    com.com.shinny.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: sh
    password: shtestpsw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create # jpa 설정이나 엔티티를 자동으로 DDL 만들어줌
    show-sql: true
    properties: # 스프링 부트에서 제공하지 않는 하이버네이트 프로퍼티즈 추가.
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100 # 연관 관계가 맵핑되어 있는 한 번에 벌크로 select 할 수 있게 해줌.
    open-in-view: false
  sql.init.mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3: # 사용자 정의 설정이기 때문에 자동완성이 안되는데 configuration-processor 추가로 자동완성 가능해짐
    decoupled-logic: true



